spring:
  application.name: turbine

turbine:
  aggregator:
    clusterConfig: default
  #配置Eureka中的serviceId列表，表明监控哪些服务
  #表示它会把所有微服务名称是product-view-service-feign 的实例信息都收集起来。
  appConfig: product-view-service-feign
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/