spring:
  application:
    name:  product-view-service-feign
  thymeleaf:
    cache: false
    #视图解析器
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
     content-type: text/html
    mode: HTML5        
  zipkin:
    base-url: http://localhost:9411

#开启断路器
feign.hystrix.enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"        